# Generated by Django 2.0 on 2017-12-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_account', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('profile_link', models.CharField(max_length=200)),
                ('account_type', models.CharField(max_length=3)),
                ('account_profile_type', models.CharField(max_length=100)),
            ],
        ),
    ]
