# Generated by Django 2.0 on 2017-12-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20171224_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='technology_type_id',
            new_name='technology_type',
        ),
    ]
