# Generated by Django 2.0 on 2017-12-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_todayquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayquote',
            name='quote_author',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
