# Generated by Django 2.0 on 2017-12-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
