# Generated by Django 2.0 on 2017-12-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
