# Generated by Django 2.0 on 2017-12-24 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0004_auto_20171224_2016'),
        ('administrator', '0003_auto_20171224_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=500)),
                ('project_url', models.URLField()),
                ('project_desc', models.TextField()),
                ('project_attachment', models.FileField(max_length=200, upload_to='')),
                ('client_location', models.CharField(max_length=200)),
                ('invited_by_client', models.CharField(max_length=5)),
                ('lead_generated', models.CharField(max_length=5)),
                ('sales_converted', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelance_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.FreelanceAccount')),
            ],
        ),
        migrations.CreateModel(
            name='LeadGeneratedContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bde.Contract')),
                ('lede_bde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.User')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SalesContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelance_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.FreelanceAccount')),
                ('sales_bde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.User')),
                ('sales_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bde.Contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='project_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bde.ProjectSize'),
        ),
    ]
