# Generated by Django 2.0 on 2017-12-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='lead_generated',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sales_converted',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
