# Generated by Django 2.0 on 2017-12-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0006_auto_20171227_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='project_attachment',
            field=models.FileField(default='null', max_length=200, upload_to=''),
        ),
    ]
