# Generated by Django 2.0 on 2017-12-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0008_auto_20171227_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadgeneratedcontract',
            old_name='lede_bde',
            new_name='lead_bde',
        ),
    ]
