# Generated by Django 2.0 on 2017-12-27 19:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_auto_20171224_2016'),
        ('bde', '0010_auto_20171227_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadgeneratedcontract',
            name='lead_bde',
        ),
        migrations.AddField(
            model_name='contract',
            name='bidder_account',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='Authentication.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadgeneratedcontract',
            name='follow_up_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 19, 10, 57, 800709)),
        ),
    ]
