# Generated by Django 2.0 on 2018-01-02 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0014_auto_20171229_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_status',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='leadgeneratedcontract',
            name='follow_up_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 0, 57, 12, 964846)),
        ),
    ]
