# Generated by Django 2.0 on 2018-01-02 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0017_auto_20180102_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadgeneratedcontract',
            name='next_follow_up_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 2, 5, 13, 311538)),
        ),
        migrations.AlterField(
            model_name='leadgeneratedcontract',
            name='follow_up_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 2, 5, 13, 311505)),
        ),
    ]
